<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="LGDN18-1071-W10" failures="1" tests="1" name="Default test" time="12.236" errors="0" timestamp="22 Nov 2018 02:51:03 GMT">
  <testcase classname="Railway.LoginTest" name="TC06" time="4.43">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	
Expected is: &amp;apos;Logout&amp;apos; displays
Actual is: &amp;apos;Log out&amp;apos; displays
 expected [Logout] but found [Log out]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:

Expected is: 'Logout' displays
Actual is: 'Log out' displays
 expected [Logout] but found [Log out]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at Utilities.Utilities.softAssertCheckTextElement(Utilities.java:57)
at Railway.LoginTest.TC06(LoginTest.java:80)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC06 -->
  <testcase classname="Railway.LoginTest" name="TC05" time="0.0">
    <ignored/>
  </testcase> <!-- TC05 -->
  <testcase classname="Railway.LoginTest" name="TC07" time="0.0">
    <ignored/>
  </testcase> <!-- TC07 -->
  <testcase classname="Railway.LoginTest" name="TC02" time="0.0">
    <ignored/>
  </testcase> <!-- TC02 -->
  <testcase classname="Railway.LoginTest" name="TC01" time="0.0">
    <ignored/>
  </testcase> <!-- TC01 -->
  <testcase classname="Railway.LoginTest" name="TC04" time="0.0">
    <ignored/>
  </testcase> <!-- TC04 -->
  <testcase classname="Railway.LoginTest" name="TC03" time="0.0">
    <ignored/>
  </testcase> <!-- TC03 -->
</testsuite> <!-- Default test -->
