<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="4" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-11-20T10:25:50Z" name="Default suite" finished-at="2018-11-20T10:27:09Z" duration-ms="79051">
    <groups>
    </groups>
    <test started-at="2018-11-20T10:25:50Z" name="Default test" finished-at="2018-11-20T10:27:09Z" duration-ms="79051">
      <class name="Railway.LoginTest">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@6a2f6f80]" started-at="2018-11-20T10:25:50Z" name="beforeMethod" finished-at="2018-11-20T10:25:57Z" duration-ms="7115" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="TC01()[pri:0, instance:Railway.LoginTest@6a2f6f80]" started-at="2018-11-20T10:25:57Z" name="TC01" description="User can log into Railway with valid username and password" finished-at="2018-11-20T10:26:01Z" duration-ms="4341" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01 -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:Railway.LoginTest@6a2f6f80]" started-at="2018-11-20T10:26:01Z" name="afterMethod" finished-at="2018-11-20T10:26:02Z" duration-ms="619" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@6a2f6f80]" started-at="2018-11-20T10:26:02Z" name="beforeMethod" finished-at="2018-11-20T10:26:08Z" duration-ms="6368" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="TC02()[pri:0, instance:Railway.LoginTest@6a2f6f80]" started-at="2018-11-20T10:26:08Z" name="TC02" description="User can&#039;t login with blank &#039;Username&#039; textbox" finished-at="2018-11-20T10:26:12Z" duration-ms="3352" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02 -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:Railway.LoginTest@6a2f6f80]" started-at="2018-11-20T10:26:12Z" name="afterMethod" finished-at="2018-11-20T10:26:12Z" duration-ms="591" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@6a2f6f80]" started-at="2018-11-20T10:26:12Z" name="beforeMethod" finished-at="2018-11-20T10:26:19Z" duration-ms="6679" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="TC03()[pri:0, instance:Railway.LoginTest@6a2f6f80]" started-at="2018-11-20T10:26:19Z" name="TC03" description="User cannot log into Railway with invalid password" finished-at="2018-11-20T10:26:24Z" duration-ms="5471" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
Expected is: There was a problem with your login and/or errors exist in your form.
Actual is: Invalid username or password. Please try again.
 expected [There was a problem with your login and/or errors exist in your form.] but found [Invalid username or password. Please try again.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
Expected is: There was a problem with your login and/or errors exist in your form.
Actual is: Invalid username or password. Please try again.
 expected [There was a problem with your login and/or errors exist in your form.] but found [Invalid username or password. Please try again.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at Railway.LoginTest.TC03(LoginTest.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC03 -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:Railway.LoginTest@6a2f6f80]" started-at="2018-11-20T10:26:24Z" name="afterMethod" finished-at="2018-11-20T10:26:25Z" duration-ms="606" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@6a2f6f80]" started-at="2018-11-20T10:26:25Z" name="beforeMethod" finished-at="2018-11-20T10:26:31Z" duration-ms="6427" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="TC04()[pri:0, instance:Railway.LoginTest@6a2f6f80]" started-at="2018-11-20T10:26:31Z" name="TC04" description="Login page displays when un-logged User clicks on &#039;Book ticket&#039; tab" finished-at="2018-11-20T10:26:35Z" duration-ms="3492" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC04 -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:Railway.LoginTest@6a2f6f80]" started-at="2018-11-20T10:26:35Z" name="afterMethod" finished-at="2018-11-20T10:26:35Z" duration-ms="612" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@6a2f6f80]" started-at="2018-11-20T10:26:35Z" name="beforeMethod" finished-at="2018-11-20T10:26:42Z" duration-ms="6617" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="TC05()[pri:0, instance:Railway.LoginTest@6a2f6f80]" started-at="2018-11-20T10:26:42Z" name="TC05" description="System shows message when user enters wrong password several times" finished-at="2018-11-20T10:26:49Z" duration-ms="7185" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
Expected is: You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.
Actual is: Invalid username or password. Please try again.
 expected [You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.] but found [Invalid username or password. Please try again.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
Expected is: You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.
Actual is: Invalid username or password. Please try again.
 expected [You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.] but found [Invalid username or password. Please try again.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at Railway.LoginTest.TC05(LoginTest.java:73)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC05 -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:Railway.LoginTest@6a2f6f80]" started-at="2018-11-20T10:26:49Z" name="afterMethod" finished-at="2018-11-20T10:26:50Z" duration-ms="593" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@6a2f6f80]" started-at="2018-11-20T10:26:50Z" name="beforeMethod" finished-at="2018-11-20T10:26:57Z" duration-ms="6734" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="TC06()[pri:0, instance:Railway.LoginTest@6a2f6f80]" started-at="2018-11-20T10:26:57Z" name="TC06" description="Additional pages display once user logged in" finished-at="2018-11-20T10:27:08Z" duration-ms="11625" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC06 -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:Railway.LoginTest@6a2f6f80]" started-at="2018-11-20T10:27:08Z" name="afterMethod" finished-at="2018-11-20T10:27:09Z" duration-ms="590" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- Railway.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
